version: 2
updates:
- package-ecosystem: "uv"
  directory: "./"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 20
- package-ecosystem: "github-actions"
  directories: ["/", "/.github/*", "/.github/actions/*"]
  schedule:
    interval: "weekly"
  groups:
    actions:
      # one PR for all GHA bumps
      patterns: ["*"]
- package-ecosystem: docker
  directory: "./"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 20
