"""Database tables and fields for the genome-depot (Alexeydata) ENIGMA database."""

GENOME_DEPOT_SCHEMA = {
    "browser_cazy_family": [
        "id",  # int not_null auto_increment,
        "cazy_id",  # varchar(12) not_null,
        "description",  # longtext not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "cazy_id" ("cazy_id")
    ],
    "browser_cog_class": [
        "id",  # int not_null auto_increment,
        "cog_id",  # varchar(1) not_null,
        "description",  # varchar(80) not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "cog_id" ("cog_id")
    ],
    "browser_config": [
        "id",  # int not_null auto_increment,
        "param",  # varchar(255) not_null,
        "value",  # varchar(255) not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "param" ("param")
    ],
    "browser_ec_number": [
        "id",  # int not_null auto_increment,
        "ec_number",  # varchar(12) not_null,
        "description",  # longtext not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "ec_number" ("ec_number")
    ],
    "browser_eggnog_description": [
        "id",  # int not_null auto_increment,
        "fingerprint",  # varchar(32) not_null,
        "description",  # longtext not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "fingerprint" ("fingerprint")
    ],
    "browser_go_term": [
        "id",  # int not_null auto_increment,
        "go_id",  # varchar(12) not_null,
        "go_namespace",  # varchar(50) not_null,
        "description",  # longtext not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "go_id" ("go_id")
    ],
    "browser_kegg_ortholog": [
        "id",  # int not_null auto_increment,
        "kegg_id",  # varchar(10) not_null,
        "description",  # longtext not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "kegg_id" ("kegg_id")
    ],
    "browser_kegg_pathway": [
        "id",  # int not_null auto_increment,
        "kegg_id",  # varchar(10) not_null,
        "description",  # varchar(200) not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "kegg_id" ("kegg_id")
    ],
    "browser_kegg_reaction": [
        "id",  # int not_null auto_increment,
        "kegg_id",  # varchar(10) not_null,
        "description",  # longtext not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "kegg_id" ("kegg_id")
    ],
    "browser_sample": [
        "id",  # int not_null auto_increment,
        "sample_id",  # varchar(100) not_null,
        "full_name",  # varchar(200) not_null,
        "description",  # varchar(250) not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "sample_id" ("sample_id")
    ],
    "browser_tag": [
        "id",  # int not_null auto_increment,
        "name",  # varchar(50) not_null,
        "description",  # varchar(300) not_null,
        "color",  # varchar(7) not_null,
        "textcolor",  # varchar(7) not_null,
        #   PRIMARY KEY ("id"),
        #   KEY "browser_tag_name_10f69202" ("name")
    ],
    "browser_taxon": [
        "id",  # int not_null auto_increment,
        "taxonomy_id",  # varchar(10) not_null,
        "eggnog_taxid",  # varchar(10) DEFAULT NULL,
        "rank",  # varchar(20) not_null,
        "parent_id",  # varchar(10) not_null,
        "name",  # varchar(100) not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "taxonomy_id" ("taxonomy_id")
    ],
    "browser_tc_family": [
        "id",  # int not_null auto_increment,
        "tc_id",  # varchar(15) not_null,
        "description",  # longtext not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "tc_id" ("tc_id")
    ],
    "browser_ortholog_group": [
        "id",  # int not_null auto_increment,
        "eggnog_id",  # varchar(15) not_null,
        "taxon_id",  # int DEFAULT NULL,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_ortholog_group_eggnog_id_taxon_id_95fd5f69_uniq" ("eggnog_id","taxon_id"),
        #   KEY "browser_ortholog_group_taxon_id_e0788f6d_fk_browser_taxon_id" ("taxon_id"),
        #   KEY "browser_ortholog_group_eggnog_id_16309ff7" ("eggnog_id"),
        #   CONSTRAINT "browser_ortholog_group_taxon_id_e0788f6d_fk_browser_taxon_id" FOREIGN KEY ("taxon_id") REFERENCES "browser_taxon" ("id")
    ],
    "browser_protein": [
        "id",  # int not_null auto_increment,
        "name",  # varchar(100) not_null,
        "length",  # int not_null,
        "protein_hash",  # varchar(32) not_null,
        "sequence",  # longtext not_null,
        "eggnog_description_id",  # int DEFAULT NULL,
        "taxonomy_id_id",  # int DEFAULT NULL,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "protein_hash" ("protein_hash"),
        #   KEY "browser_protein_eggnog_description_i_7d992f52_fk_browser_e" ("eggnog_description_id"),
        #   KEY "browser_protein_taxonomy_id_id_ec28e08a_fk_browser_taxon_id" ("taxonomy_id_id"),
        #   CONSTRAINT "browser_protein_eggnog_description_i_7d992f52_fk_browser_e" FOREIGN KEY ("eggnog_description_id") REFERENCES "browser_eggnog_description" ("id"),
        #   CONSTRAINT "browser_protein_taxonomy_id_id_ec28e08a_fk_browser_taxon_id" FOREIGN KEY ("taxonomy_id_id") REFERENCES "browser_taxon" ("id")
    ],
    "browser_protein_cazy_families": [
        "id",  # int not_null auto_increment,
        "protein_id",  # int not_null,
        "cazy_family_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_protein_cazy_fam_protein_id_cazy_family_i_98e6a206_uniq" ("protein_id","cazy_family_id"),
        #   KEY "browser_protein_cazy_cazy_family_id_0b498a05_fk_browser_c" ("cazy_family_id"),
        #   CONSTRAINT "browser_protein_cazy_cazy_family_id_0b498a05_fk_browser_c" FOREIGN KEY ("cazy_family_id") REFERENCES "browser_cazy_family" ("id"),
        #   CONSTRAINT "browser_protein_cazy_protein_id_9d8c2d94_fk_browser_p" FOREIGN KEY ("protein_id") REFERENCES "browser_protein" ("id")
    ],
    "browser_protein_cog_classes": [
        "id",  # int not_null auto_increment,
        "protein_id",  # int not_null,
        "cog_class_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_protein_cog_clas_protein_id_cog_class_id_68b06ebc_uniq" ("protein_id","cog_class_id"),
        #   KEY "browser_protein_cog__cog_class_id_628912e9_fk_browser_c" ("cog_class_id"),
        #   CONSTRAINT "browser_protein_cog__cog_class_id_628912e9_fk_browser_c" FOREIGN KEY ("cog_class_id") REFERENCES "browser_cog_class" ("id"),
        #   CONSTRAINT "browser_protein_cog__protein_id_43c3620b_fk_browser_p" FOREIGN KEY ("protein_id") REFERENCES "browser_protein" ("id")
    ],
    "browser_protein_ec_numbers": [
        "id",  # int not_null auto_increment,
        "protein_id",  # int not_null,
        "ec_number_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_protein_ec_numbers_protein_id_ec_number_id_0da1a728_uniq" ("protein_id","ec_number_id"),
        #   KEY "browser_protein_ec_n_ec_number_id_42515a8c_fk_browser_e" ("ec_number_id"),
        #   CONSTRAINT "browser_protein_ec_n_ec_number_id_42515a8c_fk_browser_e" FOREIGN KEY ("ec_number_id") REFERENCES "browser_ec_number" ("id"),
        #   CONSTRAINT "browser_protein_ec_n_protein_id_c0731ed9_fk_browser_p" FOREIGN KEY ("protein_id") REFERENCES "browser_protein" ("id")
    ],
    "browser_protein_go_terms": [
        "id",  # int not_null auto_increment,
        "protein_id",  # int not_null,
        "go_term_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_protein_go_terms_protein_id_go_term_id_e8a154a9_uniq" ("protein_id","go_term_id"),
        #   KEY "browser_protein_go_t_go_term_id_fff0186d_fk_browser_g" ("go_term_id"),
        #   CONSTRAINT "browser_protein_go_t_go_term_id_fff0186d_fk_browser_g" FOREIGN KEY ("go_term_id") REFERENCES "browser_go_term" ("id"),
        #   CONSTRAINT "browser_protein_go_t_protein_id_8eb220cd_fk_browser_p" FOREIGN KEY ("protein_id") REFERENCES "browser_protein" ("id")
    ],
    "browser_protein_kegg_orthologs": [
        "id",  # int not_null auto_increment,
        "protein_id",  # int not_null,
        "kegg_ortholog_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_protein_kegg_ort_protein_id_kegg_ortholog_20402b1d_uniq" ("protein_id","kegg_ortholog_id"),
        #   KEY "browser_protein_kegg_kegg_ortholog_id_2495a14d_fk_browser_k" ("kegg_ortholog_id"),
        #   CONSTRAINT "browser_protein_kegg_kegg_ortholog_id_2495a14d_fk_browser_k" FOREIGN KEY ("kegg_ortholog_id") REFERENCES "browser_kegg_ortholog" ("id"),
        #   CONSTRAINT "browser_protein_kegg_protein_id_ca765f00_fk_browser_p" FOREIGN KEY ("protein_id") REFERENCES "browser_protein" ("id")
    ],
    "browser_protein_kegg_pathways": [
        "id",  # int not_null auto_increment,
        "protein_id",  # int not_null,
        "kegg_pathway_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_protein_kegg_pat_protein_id_kegg_pathway__3de66af8_uniq" ("protein_id","kegg_pathway_id"),
        #   KEY "browser_protein_kegg_kegg_pathway_id_47214837_fk_browser_k" ("kegg_pathway_id"),
        #   CONSTRAINT "browser_protein_kegg_kegg_pathway_id_47214837_fk_browser_k" FOREIGN KEY ("kegg_pathway_id") REFERENCES "browser_kegg_pathway" ("id"),
        #   CONSTRAINT "browser_protein_kegg_protein_id_f703bb73_fk_browser_p" FOREIGN KEY ("protein_id") REFERENCES "browser_protein" ("id")
    ],
    "browser_protein_kegg_reactions": [
        "id",  # int not_null auto_increment,
        "protein_id",  # int not_null,
        "kegg_reaction_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_protein_kegg_rea_protein_id_kegg_reaction_956ee52f_uniq" ("protein_id","kegg_reaction_id"),
        #   KEY "browser_protein_kegg_kegg_reaction_id_b069e895_fk_browser_k" ("kegg_reaction_id"),
        #   CONSTRAINT "browser_protein_kegg_kegg_reaction_id_b069e895_fk_browser_k" FOREIGN KEY ("kegg_reaction_id") REFERENCES "browser_kegg_reaction" ("id"),
        #   CONSTRAINT "browser_protein_kegg_protein_id_c42ec7ca_fk_browser_p" FOREIGN KEY ("protein_id") REFERENCES "browser_protein" ("id")
    ],
    "browser_protein_ortholog_groups": [
        "id",  # int not_null auto_increment,
        "protein_id",  # int not_null,
        "ortholog_group_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_protein_ortholog_protein_id_ortholog_grou_00502bdd_uniq" ("protein_id","ortholog_group_id"),
        #   KEY "browser_protein_orth_ortholog_group_id_89ef3520_fk_browser_o" ("ortholog_group_id"),
        #   CONSTRAINT "browser_protein_orth_ortholog_group_id_89ef3520_fk_browser_o" FOREIGN KEY ("ortholog_group_id") REFERENCES "browser_ortholog_group" ("id"),
        #   CONSTRAINT "browser_protein_orth_protein_id_16a9accd_fk_browser_p" FOREIGN KEY ("protein_id") REFERENCES "browser_protein" ("id")
    ],
    "browser_protein_tc_families": [
        "id",  # int not_null auto_increment,
        "protein_id",  # int not_null,
        "tc_family_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_protein_tc_famil_protein_id_tc_family_id_dd3a5cca_uniq" ("protein_id","tc_family_id"),
        #   KEY "browser_protein_tc_f_tc_family_id_3202c6dc_fk_browser_t" ("tc_family_id"),
        #   CONSTRAINT "browser_protein_tc_f_protein_id_7bba3b67_fk_browser_p" FOREIGN KEY ("protein_id") REFERENCES "browser_protein" ("id"),
        #   CONSTRAINT "browser_protein_tc_f_tc_family_id_3202c6dc_fk_browser_t" FOREIGN KEY ("tc_family_id") REFERENCES "browser_tc_family" ("id")
    ],
    "browser_sample_metadata": [
        "id",  # int not_null auto_increment,
        "source",  # varchar(30) not_null,
        "url",  # varchar(250) not_null,
        "key",  # varchar(250) not_null,
        "value",  # longtext not_null,
        "sample_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   KEY "browser_sample_metadata_sample_id_7e68900d_fk_browser_sample_id" ("sample_id"),
        #   CONSTRAINT "browser_sample_metadata_sample_id_7e68900d_fk_browser_sample_id" FOREIGN KEY ("sample_id") REFERENCES "browser_sample" ("id")
    ],
    "browser_strain": [
        "id",  # int not_null auto_increment,
        "strain_id",  # varchar(100) not_null,
        "full_name",  # varchar(200) not_null,
        "order",  # varchar(100) not_null,
        "taxon_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "strain_id" ("strain_id"),
        #   KEY "browser_strain_taxon_id_b809e6e5_fk_browser_taxon_id" ("taxon_id"),
        #   CONSTRAINT "browser_strain_taxon_id_b809e6e5_fk_browser_taxon_id" FOREIGN KEY ("taxon_id") REFERENCES "browser_taxon" ("id")
    ],
    "browser_strain_metadata": [
        "id",  # int not_null auto_increment,
        "source",  # varchar(30) not_null,
        "url",  # varchar(250) not_null,
        "key",  # varchar(250) not_null,
        "value",  # longtext not_null,
        "strain_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   KEY "browser_strain_metadata_strain_id_ec4e0f0a_fk_browser_strain_id" ("strain_id"),
        #   CONSTRAINT "browser_strain_metadata_strain_id_ec4e0f0a_fk_browser_strain_id" FOREIGN KEY ("strain_id") REFERENCES "browser_strain" ("id")
    ],
    "django_admin_log": [
        "id",  # int not_null auto_increment,
        "action_time",  # datetime(6) not_null,
        "object_id",  # longtext,
        "object_repr",  # varchar(200) not_null,
        "action_flag",  # smallint unsigned not_null,
        "change_message",  # longtext not_null,
        "content_type_id",  # int DEFAULT NULL,
        "user_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   KEY "django_admin_log_content_type_id_c4bce8eb_fk_django_co" ("content_type_id"),
        #   KEY "django_admin_log_user_id_c564eba6_fk_auth_user_id" ("user_id"),
        #   CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id"),
        #   CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id"),
        #   CONSTRAINT "django_admin_log_chk_1" CHECK (("action_flag" >= 0))
    ],
    "auth_group_permissions": [
        "id",  # int not_null auto_increment,
        "group_id",  # int not_null,
        "permission_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ("group_id","permission_id"),
        #   KEY "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" ("permission_id"),
        #   CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id"),
        #   CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id")
    ],
    "browser_genome": [
        "id",  # int not_null auto_increment,
        "name",  # varchar(200) not_null,
        "description",  # longtext not_null,
        "contigs",  # int unsigned not_null,
        "size",  # int unsigned not_null,
        "genes",  # int unsigned not_null,
        "json_url",  # varchar(200) not_null,
        "pub_date",  # datetime(6) not_null,
        "external_url",  # varchar(200) not_null,
        "external_id",  # varchar(40) not_null,
        "gbk_filepath",  # varchar(200) not_null,
        "sample_id",  # int DEFAULT NULL,
        "strain_id",  # int DEFAULT NULL,
        "taxon_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "name" ("name"),
        #   KEY "browser_genome_sample_id_75fbf0ab_fk_browser_sample_id" ("sample_id"),
        #   KEY "browser_genome_strain_id_f18624c7_fk_browser_strain_id" ("strain_id"),
        #   KEY "browser_genome_taxon_id_f69a69a0_fk_browser_taxon_id" ("taxon_id"),
        #   CONSTRAINT "browser_genome_sample_id_75fbf0ab_fk_browser_sample_id" FOREIGN KEY ("sample_id") REFERENCES "browser_sample" ("id"),
        #   CONSTRAINT "browser_genome_strain_id_f18624c7_fk_browser_strain_id" FOREIGN KEY ("strain_id") REFERENCES "browser_strain" ("id"),
        #   CONSTRAINT "browser_genome_taxon_id_f69a69a0_fk_browser_taxon_id" FOREIGN KEY ("taxon_id") REFERENCES "browser_taxon" ("id"),
        #   CONSTRAINT "browser_genome_chk_1" CHECK (("contigs" >= 0)),
        #   CONSTRAINT "browser_genome_chk_2" CHECK (("size" >= 0)),
        #   CONSTRAINT "browser_genome_chk_3" CHECK (("genes" >= 0))
    ],
    "browser_genome_tags": [
        "id",  # int not_null auto_increment,
        "genome_id",  # int not_null,
        "tag_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_genome_tags_genome_id_tag_id_a75ec35f_uniq" ("genome_id","tag_id"),
        #   KEY "browser_genome_tags_tag_id_cbc127ca_fk_browser_tag_id" ("tag_id"),
        #   CONSTRAINT "browser_genome_tags_genome_id_dbeb3fc4_fk_browser_genome_id" FOREIGN KEY ("genome_id") REFERENCES "browser_genome" ("id"),
        #   CONSTRAINT "browser_genome_tags_tag_id_cbc127ca_fk_browser_tag_id" FOREIGN KEY ("tag_id") REFERENCES "browser_tag" ("id")
    ],
    "browser_regulon": [
        "id",  # int not_null auto_increment,
        "name",  # varchar(50) not_null,
        "description",  # longtext not_null,
        "genome_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   KEY "browser_regulon_genome_id_0da5b8a6_fk_browser_genome_id" ("genome_id"),
        #   KEY "browser_regulon_name_961e8e34" ("name"),
        #   CONSTRAINT "browser_regulon_genome_id_0da5b8a6_fk_browser_genome_id" FOREIGN KEY ("genome_id") REFERENCES "browser_genome" ("id")
    ],
    "browser_contig": [
        "id",  # int not_null auto_increment,
        "contig_id",  # varchar(100) not_null,
        "name",  # varchar(250) not_null,
        "size",  # int not_null,
        "genome_id",  # int DEFAULT NULL,
        #   PRIMARY KEY ("id"),
        #   KEY "browser_contig_genome_id_a98adf71_fk_browser_genome_id" ("genome_id"),
        #   CONSTRAINT "browser_contig_genome_id_a98adf71_fk_browser_genome_id" FOREIGN KEY ("genome_id") REFERENCES "browser_genome" ("id")
    ],
    "browser_operon": [
        "id",  # int not_null auto_increment,
        "name",  # varchar(250) not_null,
        "start",  # int not_null,
        "end",  # int not_null,
        "strand",  # int not_null,
        "contig_id",  # int DEFAULT NULL,
        "genome_id",  # int DEFAULT NULL,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_operon_genome_id_name_eae14085_uniq" ("genome_id","name"),
        #   KEY "browser_operon_contig_id_a4110648_fk_browser_contig_id" ("contig_id"),
        #   CONSTRAINT "browser_operon_contig_id_a4110648_fk_browser_contig_id" FOREIGN KEY ("contig_id") REFERENCES "browser_contig" ("id"),
        #   CONSTRAINT "browser_operon_genome_id_3e25f150_fk_browser_genome_id" FOREIGN KEY ("genome_id") REFERENCES "browser_genome" ("id")
    ],
    "browser_site": [
        "id",  # int not_null auto_increment,
        "name",  # varchar(50) not_null,
        "type",  # varchar(20) not_null,
        "start",  # int not_null,
        "end",  # int not_null,
        "strand",  # int not_null,
        "sequence",  # longtext not_null,
        "contig_id",  # int DEFAULT NULL,
        "genome_id",  # int not_null,
        "regulon_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_site_regulon_id_name_e35362d1_uniq" ("regulon_id","name"),
        #   KEY "browser_site_contig_id_54dc54ad_fk_browser_contig_id" ("contig_id"),
        #   KEY "browser_site_genome_id_47862a9e_fk_browser_genome_id" ("genome_id"),
        #   CONSTRAINT "browser_site_contig_id_54dc54ad_fk_browser_contig_id" FOREIGN KEY ("contig_id") REFERENCES "browser_contig" ("id"),
        #   CONSTRAINT "browser_site_genome_id_47862a9e_fk_browser_genome_id" FOREIGN KEY ("genome_id") REFERENCES "browser_genome" ("id"),
        #   CONSTRAINT "browser_site_regulon_id_64cf9422_fk_browser_regulon_id" FOREIGN KEY ("regulon_id") REFERENCES "browser_regulon" ("id")
    ],
    "browser_site_operons": [
        "id",  # int not_null auto_increment,
        "site_id",  # int not_null,
        "operon_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_site_operons_site_id_operon_id_4e1afc7b_uniq" ("site_id","operon_id"),
        #   KEY "browser_site_operons_operon_id_f202c4b2_fk_browser_operon_id" ("operon_id"),
        #   CONSTRAINT "browser_site_operons_operon_id_f202c4b2_fk_browser_operon_id" FOREIGN KEY ("operon_id") REFERENCES "browser_operon" ("id"),
        #   CONSTRAINT "browser_site_operons_site_id_842b2fa4_fk_browser_site_id" FOREIGN KEY ("site_id") REFERENCES "browser_site" ("id")
    ],
    "browser_gene": [
        "id",  # int not_null auto_increment,
        "name",  # varchar(50) not_null,
        "locus_tag",  # varchar(50) not_null,
        "type",  # varchar(20) not_null,
        "start",  # int not_null,
        "end",  # int not_null,
        "strand",  # int not_null,
        "function",  # varchar(250) not_null,
        "contig_id",  # int DEFAULT NULL,
        "genome_id",  # int not_null,
        "operon_id",  # int DEFAULT NULL,
        "protein_id",  # int DEFAULT NULL,
        #   PRIMARY KEY ("id"),
        #   KEY "browser_gene_genome_id_fb585326_fk_browser_genome_id" ("genome_id"),
        #   KEY "browser_gene_operon_id_72d8bf49_fk_browser_operon_id" ("operon_id"),
        #   KEY "browser_gene_protein_id_e73b3cb7_fk_browser_protein_id" ("protein_id"),
        #   KEY "browser_gene_contig_id_b190eedc_fk_browser_contig_id" ("contig_id"),
        #   KEY "browser_gene_name_edef1e56" ("name"),
        #   KEY "browser_gene_locus_tag_7f163d55" ("locus_tag"),
        #   KEY "browser_gene_function_d53e81f6" ("function"),
        #   CONSTRAINT "browser_gene_contig_id_b190eedc_fk_browser_contig_id" FOREIGN KEY ("contig_id") REFERENCES "browser_contig" ("id"),
        #   CONSTRAINT "browser_gene_genome_id_fb585326_fk_browser_genome_id" FOREIGN KEY ("genome_id") REFERENCES "browser_genome" ("id"),
        #   CONSTRAINT "browser_gene_operon_id_72d8bf49_fk_browser_operon_id" FOREIGN KEY ("operon_id") REFERENCES "browser_operon" ("id"),
        #   CONSTRAINT "browser_gene_protein_id_e73b3cb7_fk_browser_protein_id" FOREIGN KEY ("protein_id") REFERENCES "browser_protein" ("id")
    ],
    "browser_regulon_regulators": [
        "id",  # int not_null auto_increment,
        "regulon_id",  # int not_null,
        "gene_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_regulon_regulators_regulon_id_gene_id_31f79fdf_uniq" ("regulon_id","gene_id"),
        #   KEY "browser_regulon_regulators_gene_id_9397e934_fk_browser_gene_id" ("gene_id"),
        #   CONSTRAINT "browser_regulon_regu_regulon_id_05cf48a4_fk_browser_r" FOREIGN KEY ("regulon_id") REFERENCES "browser_regulon" ("id"),
        #   CONSTRAINT "browser_regulon_regulators_gene_id_9397e934_fk_browser_gene_id" FOREIGN KEY ("gene_id") REFERENCES "browser_gene" ("id")
    ],
    "browser_site_genes": [
        "id",  # int not_null auto_increment,
        "site_id",  # int not_null,
        "gene_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   UNIQUE KEY "browser_site_genes_site_id_gene_id_117d2308_uniq" ("site_id","gene_id"),
        #   KEY "browser_site_genes_gene_id_e364c0fc_fk_browser_gene_id" ("gene_id"),
        #   CONSTRAINT "browser_site_genes_gene_id_e364c0fc_fk_browser_gene_id" FOREIGN KEY ("gene_id") REFERENCES "browser_gene" ("id"),
        #   CONSTRAINT "browser_site_genes_site_id_1c58c050_fk_browser_site_id" FOREIGN KEY ("site_id") REFERENCES "browser_site" ("id")
    ],
    "browser_annotation": [
        "id",  # int not_null auto_increment,
        "source",  # varchar(30) not_null,
        "url",  # varchar(300) not_null,
        "key",  # varchar(30) not_null,
        "value",  # varchar(50) not_null,
        "note",  # longtext not_null,
        "gene_id_id",  # int not_null,
        #   PRIMARY KEY ("id"),
        #   KEY "browser_annotation_gene_id_id_cb275c89_fk_browser_gene_id" ("gene_id_id"),
        #   KEY "browser_annotation_source_79ad3072" ("source"),
        #   KEY "browser_annotation_key_fbcc98fb" ("key"),
        #   KEY "browser_annotation_value_8d85b11e" ("value"),
        #   CONSTRAINT "browser_annotation_gene_id_id_cb275c89_fk_browser_gene_id" FOREIGN KEY ("gene_id_id") REFERENCES "browser_gene" ("id")
    ],
}
