<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root" type="rootType"/>
    <xs:complexType name="rootType">
        <xs:sequence>
            <xs:element name="requiredSingle" type="xs:string"/>
            <xs:element name="optionalSingle" type="xs:string" minOccurs="0"/>
            <xs:element name="optionalRepeated" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="requiredRepeated" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="boundedRepeated" type="xs:string" minOccurs="0" maxOccurs="2"/>
            <xs:element name="neverOccurs" type="xs:string" minOccurs="0" maxOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>
