<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="UniRef50" type="UniRefType"/>
    <xs:element name="UniRef90" type="UniRefType"/>
    <xs:element name="UniRef100" type="UniRefType"/>
    <xs:complexType name="UniRefType">
        <xs:sequence>
            <xs:element name="entry" type="entryType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="entryType">
        <xs:sequence>
            <xs:element name="property" type="propertyType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="representativeMember" type="memberType"/>
            <xs:element name="member" type="memberType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="memberType">
        <xs:sequence>
            <xs:element name="dbReference" type="dbReferenceType"/>
            <xs:element name="sequence" type="sequenceType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="dbReferenceType">
        <xs:sequence>
            <xs:element name="property" type="propertyType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="propertyType">
        <xs:attribute name="type" type="xs:string"/>
        <xs:attribute name="value" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="sequenceType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="length" type="xs:int"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>
