[normalize.data_writer]
disable_compression = "false"

[runtime]
http_show_error_body = "true"
log_level = "INFO"
log_format = "JSON"

# REST Client retries
# default: 60
request_timeout = 60
# default: 5
request_max_attempts = 2
# default: 1
request_backoff_factor = 1.5
# default: 300
request_max_retry_delay = 600

# do not raise an error if a job fails
load.raise_on_failed_jobs = "false"

[extract]
workers = 10

# 'local_fs' destination: save to the `output` directory
[destination.local_fs]
destination_type = "filesystem"
bucket_url = "/output_dir"

[destination.s3]
destination_type = "filesystem"
bucket_url = "s3://cts/io/ialarmedalien/datasets/cts_output/bloooooop"

[data_writer]
# set buffer size for extract and normalize stages
buffer_max_items = 100000
# files will rotate after 100_000_000 items have been written
file_max_items = 100000000
# files will rotate when file size is greater than 1_000 MB
file_max_bytes = 1000000000
