"""Utilities for interacting with Spark."""

from logging import Logger, getLogger
from typing import Final

from pyspark.sql import DataFrame, DataFrameWriterV2, SparkSession

logger: Logger = getLogger(__name__)


APPEND: Final[str] = "append"
CREATE: Final[str] = "create"
CREATE_OR_REPLACE: Final[str] = "createOrReplace"
REPLACE: Final[str] = "replace"

# requires argument
OVERWRITE: Final[str] = "overwrite"

WRITE_MODE_V2 = [APPEND, CREATE, CREATE_OR_REPLACE, REPLACE, OVERWRITE]


DEFAULT_APP_NAME: Final[str] = "cdm_data_loader"
DEFAULT_NAMESPACE: Final[str] = "default"
DEFAULT_WRITE_MODE: Final[str] = APPEND


def get_spark(
    app_name: str | None = None,
    **kwargs,
) -> SparkSession:
    """Set up a Spark session and namespace.

    If no app_name is provided, the function will use the string "cdm_data_loader".

    :param app_name: name for the app (used for the Spark session), defaults to None
    :type app_name: str, optional
    :param kwargs: extra arguments to supply to the spark session
    :type kwargs: dict[str, Any] | None
    :return: a Spark session
    :rtype: SparkSession
    """
    from berdl_notebook_utils.setup_spark_session import get_spark_session  # noqa: PLC0415

    return get_spark_session(app_name or DEFAULT_APP_NAME, **kwargs)


def set_up_workspace(
    app_name: str | None = None,
    namespace: str | None = None,
    tenant_name: str | None = None,
    **kwargs: str | int | bool | dict | None,
) -> tuple[SparkSession, str]:
    """Set up a Spark session and namespace.

    If no app_name is provided, the function will use the string "cdm_data_loader".

    N.b. this is the only function where the "raw" namespace and tenant are specified. All other functions use
    the catalog_db namespace generated by notebook_utils (from parent spark_notebook docker container)

    :param app_name: name for the app (used for the Spark session), defaults to None
    :type app_name: str, optional
    :param namespace: namespace for data I/O, defaults to None
    :type namespace: str, optional
    :param tenant_name: name of the tenant, if applicable; defaults to None
    :type tenant_name: str, optional
    :param kwargs: extra arguments to supply to the spark session
    :type kwargs: dict[str, Any] | None
    :return: a Spark session and the BERDL-approved namespace
    :rtype: tuple[SparkSession, str]
    """
    from berdl_notebook_utils.spark.database import create_namespace_if_not_exists  # noqa: PLC0415

    spark = get_spark(app_name or DEFAULT_APP_NAME, **kwargs)
    # if the namespace has already been created, this will return the doctored namespace
    catalog_db = create_namespace_if_not_exists(spark, namespace or DEFAULT_NAMESPACE, tenant_name=tenant_name)
    return (spark, catalog_db)


def write_table_v2(sdf: DataFrame, catalog_db: str, table: str, mode: str = DEFAULT_WRITE_MODE) -> None:
    """Write data as database tables and register it in the catalog.

    :param sdf: data frame to be written
    :type sdf: DataFrame
    :param catalog_db: catalog database name assigned by `set_up_workspace` or `create_namespace_if_not_exists`
    :type catalog_db: str
    :param table: table name
    :type table: str
    :param mode: spark write mode; one of the modes specified in WRITE_MODE_V2
    :type mode: str
    """
    catalog_db_table = f"{catalog_db}.{table}"
    if mode not in WRITE_MODE_V2:
        msg = f"Invalid mode supplied for writing table {catalog_db_table}: {mode}"
        logger.error(msg)
        raise ValueError(msg)

    if sdf is None or not isinstance(sdf, DataFrame) or sdf.isEmpty():
        logger.warning("No data to write to %s", catalog_db_table)
        return

    df_writer: DataFrameWriterV2 = sdf.to(sdf.schema).writeTo(catalog_db_table)

    logger.info("Writing table %s in mode %s (rows=%d)", catalog_db_table, mode, sdf.count())
    logger.debug(sdf.printSchema())
    logger.debug(sdf.show(10, truncate=False))

    # set any other stuff

    # run the fn - append/create/replace
    try:
        getattr(df_writer, mode)()
        logger.info("Saved managed table %s (rows=%d)", catalog_db_table, sdf.count())
    except Exception:
        logger.exception("Error writing managed table %s", catalog_db_table)
        raise

    return
